# Import Libraries needed by this notebook

In [1]:
import numpy as np
import torch
import tensorflow as tf

# Define NumPy array using List and also using Tuple

In [5]:
an_array = np.array([1, 3, 5, 7, 9])

print(an_array)
#Data type of array
print(an_array.dtype)

[1 3 5 7 9]
int64


In [6]:
an_array = np.array((1, 3, 5, 7, 9))

print(an_array)
print(type(an_array))

[1 3 5 7 9]
<class 'numpy.ndarray'>


# One Dimension Array

In [9]:
one_d_array = np.array([1,3,5,7,9])

print(f"Number of Dimensions:: ${one_d_array.ndim}")
print(one_d_array[1])

Number of Dimensions:: $1
3


# Two Dimension Array

In [12]:
two_d_array = np.array([[1,3,5],[7,9,10]])

print(f"Number of Dimensions:: ${two_d_array.ndim}")
print(two_d_array[1, 2])

Number of Dimensions:: $2
10


# Three Dimension Array

In [17]:
three_d_array = np.array([[[1,3,5],[7,9,10]],[[2,5,7],[4,5,9]]] )

print(f"Number of Dimensions:: ${three_d_array.ndim}")
print(three_d_array[0, 1, 2])
print(f"Shape: ${three_d_array.shape}")

Number of Dimensions:: $3
10
Shape: $(2, 2, 3)


# Size and No of bytes in array

In [19]:
print(f"Size of array:: ${three_d_array.size}")
print(f"Size od array in Bytes:: ${three_d_array.nbytes}")

Size of array:: $12
Size od array in Bytes:: $96


# Universal Method: np.arange



*   Create an array of 100 elemets
*   Create an array start with 20 and ends at 100
*   Create an array start with 20 and ends at 100 and perform jumps of 20.
*   arange method doesn't create a list. It iterates and gives you numbers. These kind of objects are iterators. They iterate but never create.
*   But you can create a list by calling list method




In [6]:
arange_array = np.arange(100)
print(arange_array)

arange_array = np.arange(20,100)
print(arange_array)

arange_array = np.arange(20,100,20)
print(arange_array)

arange_list = list(np.arange(20,100,20))
print(arange_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
[20 40 60 80]
[np.int64(20), np.int64(40), np.int64(60), np.int64(80)]


# NumPy.random.permutation



*   Permutations randomly shuffle all the elements in the array



In [11]:
permutation_array = np.random.permutation(np.arange(10))
print(permutation_array)

[7 4 1 8 3 2 6 9 0 5]


# NumPy.random.randint



*   This method creates a random integer b/w given range



In [15]:
rand_integer_value = np.random.randint(20,30)
print(rand_integer_value)
print(type(rand_integer_value))

22
<class 'int'>


# NumPy.random.rand

*   This creates an array of random numbers
*   All random numbers are b/w zero and one.
*   You can also use this to create multi-dimension array. You will pass arguments acording to the dimensions.



# How You read multi-dimension array


*   Let's assume the 4-dimensions array dimensions are (2,3,4,5)
*   There are two arrays that are three dimensional
*   Each three dimensional array has 3 two-dimensional array
*   Each two dimensional array has 4 one-dimensional array
*   Each one dimensional array has 5 elements



In [ ]:
rand_array = np.random.rand(10)
print(rand_array)
print("------------------------------")
rand_two_d_array = np.random.rand(2,3)
print(rand_two_d_array)
print("------------------------------")
rand_three_d_array = np.random.rand(2,3,4)
print(rand_three_d_array)
print(rand_three_d_array.ndim)
print("------------------------------")
rand_four_d_array = np.random.rand(2,3,4,5)
print(rand_four_d_array)
print(rand_four_d_array.ndim)

# NumPy.random.randn


*   This creates an array of normal random numbers
*   The distribution of this data Gaussian distribution and on graph it looks like bell.
*   Gaussian (or Normal) distribution is a symmetric, bell-shaped probability curve defined by its mean (\(\mu \))



In [18]:
randn_array = np.random.randn(20)
print(randn_array)

[ 2.11992318  0.11505015 -0.2576993   1.56367686 -0.19156697  0.69542538
  0.29951221  1.01679824 -2.69069708  0.34036446 -1.63505639  0.64253658
  0.27645703  0.27223814  0.38571256  0.44496633  0.74107149 -1.40298664
  0.19134072  0.43849498]


# NumPy.reshape


*   This changes the shape of the array
*   An array of shape 1-dimension can be changed to 2 dimension array. Provided the count of the elements supports that.
*   If you create a one-dimensional array of 100 elements. Reshape it to two-dimensional array which would be matrix. Give arguments (4, 25).
*   Now this is two dimensional array and it's matrix
*   4 means rows in the matrix and 25 means columns in the matrix



In [ ]:
create_matrix = np.arange(100).reshape(4, 25)

print(create_matrix.shape)
print("-------------------------")
print("4 rows and 25 columns of the matrix")
print("-------------------------")
print(create_matrix)

# NumPy.reshape


*   This changes the shape of the array
*   Create a three dimensional array
*   If elements are total hundered, then multiple of all dimensions has to be hundred.
*   For example, convert an array of hundred elements to 3-d array with shape (4, 5, 5). So 4 * 5 * 5 = 100

In [ ]:
create_three_d_array = np.arange(100).reshape(4, 5, 5)
print(create_three_d_array)

# NumPy.ones

*   This gives an array of all ones.



In [ ]:
ones_array = np.ones(10)

print(ones_array.shape)
print("-------------------------")
print(ones_array.ndim)
print("-------------------------")
print(ones_array)


# NumPy.zeros


*   This gives an array of all zeros.




In [ ]:
zeros_array = np.zeros(10)

print(zeros_array.shape)
print("-------------------------")
print(zeros_array.ndim)
print("-------------------------")
print(zeros_array)


# Find an element in an array

In [37]:
an_array = np.arange(100)
print(an_array)
an_element = np.argwhere(an_array == 50)[0][0]
print(an_element)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
50


# Create a matrix

In [45]:
a_matrix = np.round(10 * np.random.rand(5, 4))
print(a_matrix)
print("-------------------------")
print(a_matrix.shape)
print("-------------------------")
print(a_matrix[1,2])
print("------------Read Complete row 1-------------")
print(a_matrix[1,:])
print("------------Read Complete column 1-------------")
print(a_matrix[:,1])

[[ 1.  0.  7.  2.]
 [ 6.  6. 10.  7.]
 [ 3.  9.  2.  1.]
 [ 6.  7.  9.  0.]
 [ 1.  1.  6.  3.]]
-------------------------
(5, 4)
-------------------------
10.0
------------Read Complete row 1-------------
[ 6.  6. 10.  7.]
------------Read Complete column 1-------------
[0. 6. 9. 7. 1.]


# Matrix Transpose

In [44]:
a_transpose = a_matrix.T
print(a_transpose)
print("-------------------------")
print(a_transpose.shape)
print("-------------------------")
print(a_transpose[1,2])
print("------------Read Complete row 1-------------")
print(a_transpose[1,:])
print("------------Read Complete column 1-------------")
print(a_transpose[:,1])

[[ 0.  6.  8.  3.  1.]
 [ 6.  1.  9.  1.  3.]
 [ 5.  0.  4. 10.  3.]
 [ 2.  3.  3. 10.  8.]]
-------------------------
(4, 5)
-------------------------
9.0
------------Read Complete row 1-------------
[6. 1. 9. 1. 3.]
------------Read Complete column 1-------------
[6. 1. 0. 3.]


# In matrix, sort all the columns

In [48]:
a_transpose.sort(axis = 0)
print(a_transpose)
print("-------------------------")
print(a_transpose.shape)
print("-------------------------")
print(a_transpose[1,2])
print("------------Read Complete row 1-------------")
print(a_transpose[1,:])
print("------------Read Complete column 1-------------")
print(a_transpose[:,1])

[[ 0.  0.  3.  1.  1.]
 [ 2.  1.  4.  3.  3.]
 [ 5.  3.  8. 10.  3.]
 [ 6.  6.  9. 10.  8.]]
-------------------------
(4, 5)
-------------------------
4.0
------------Read Complete row 1-------------
[2. 1. 4. 3. 3.]
------------Read Complete column 1-------------
[0. 1. 3. 6.]


# In matrix, sort all the rows

In [ ]:
a_transpose.sort(axis = 1)
print(a_transpose)
print("-------------------------")
print(a_transpose.shape)
print("-------------------------")
print(a_transpose[1,2])
print("------------Read Complete row 1-------------")
print(a_transpose[1,:])
print("------------Read Complete column 1-------------")
print(a_transpose[:,1])

# Array Masking OR Fancy Indexing


*   Masking is you pass a condition and then only elements satisfying the condition returns
*   It creates a copy.



In [ ]:
masking_matrix = np.round(10 * np.random.rand(5, 4))

masked_array = masking_matrix[masking_matrix > 5.]
print(masking_matrix)
print("------------------------")
print(masked_array)

masked_array = masking_matrix[(masking_matrix > 4.) & (masking_matrix < 8.)]
print("------------------------")
print(masked_array)

# NumPy Boradcasting


*   NumPy allows you to add/multiply scalar values to arrays.
*   It gets applied to every element
*   Broadcasting also allows you to add columns/rows to an array/matrix/n-dimension

In [58]:
broadcasting_matrix = np.round(10 * np.random.rand(5, 4))
print(broadcasting_matrix)
print(broadcasting_matrix + 5)

[[8. 0. 5. 5.]
 [4. 5. 2. 7.]
 [8. 9. 3. 8.]
 [2. 6. 6. 3.]
 [8. 5. 7. 1.]]
[[13.  5. 10. 10.]
 [ 9. 10.  7. 12.]
 [13. 14.  8. 13.]
 [ 7. 11. 11.  8.]
 [13. 10. 12.  6.]]


# np.vstack() — Vertical Stack (Row-wise)


*   Stacks arrays on top of each other
*   Arrays must have the same number of columns
*   1D arrays are treated as rows



In [59]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


# np.hstack() — Horizontal Stack (Column-wise)


*   Stacks arrays side by side
*   Arrays must have the same number of rows
*   For 1D arrays, it concatenates along the only axis


In [61]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
print(np.vstack((a, b)))
print("------------------------")
print(np.hstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------------------------
[[1 2 5 6]
 [3 4 7 8]]


# NumPy Speed Test


In [64]:
B = np.random.rand(1000000)

%timeit sum(B)
print("----------------------------------")
%timeit np.sum(B)

122 ms ± 31.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
----------------------------------
397 µs ± 15.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
